#!/bin/sh

BASEDIR="en/" # root of translatable sources
PROJECT="ktutorial-editor" # project name
WDIR=`pwd` # working dir

echo "Extracting messages"
cd ${BASEDIR}
docbookFiles=`find . -name '*.docbook'`
for docbookFile in $docbookFiles; do
    xml2pot $docbookFile > ${WDIR}/$docbookFile.pot
done
echo "Done extracting messages"

 
echo "Concatenating pot files"
cd ${WDIR}
temporaryPotFiles=`find . -name '*.docbook.pot'`
msgcat $temporaryPotFiles -o ${PROJECT}-handbook.pot

# The PO metadata generated by xml2pot contains specific KDE information, like
# mailing list or bugzilla addresses. To avoid KTutorial localization problems
# be sent there, a custom POT file containing only the desired header (one
# generated by gettext utils) is added before the handbook POT file. As the
# header POT file only contains the header, it can be used to replace the one
# generated by xml2pot.
# However, the header POT file has to be updated to keep the POT-Creation-Date
# attribute to the current creation date.
potCreationDate=`sed -nr 's/"(POT-Creation-Date:.*)\\\n"/\1/p' ${PROJECT}-handbook.pot`
sed --in-place "s/^\"POT-Creation-Date:.*\"/\"$potCreationDate\\\n\"/" header.pot
msgcat --use-first header.pot ${PROJECT}-handbook.pot -o ${PROJECT}-handbook.pot
echo "Done concatenating pot files"

 
echo "Merging translations"
cd ${WDIR}
catalogs=`find . -name '*.po'`
for cat in $catalogs; do
    echo $cat
    msgmerge -o $cat.new $cat ${PROJECT}-handbook.pot
    mv $cat.new $cat
done
echo "Done merging translations"

 
echo "Cleaning up"
cd ${WDIR}
rm $temporaryPotFiles
echo "Done"
